#!/usr/bin/awk -f

BEGIN{
    FS=","
    printf("%-40s%-26s%-18s%-17s%8s\n\n\n", "Movie", "Genre", "Produced by", "# of Employees", "Earnings")
    print("All the movies:")
}
{
    indOfFirstQuote = index($1, "\"")
    firstPart = ""
    if(indOfFirstQuote != 0){
        firstPart = substr($1, 2, length($1))
        secondPart = substr($2, 1, length($2) - 1)
        $1 = firstPart "," secondPart
        for(i = 2; i <= NF; i++){
            $i = $(i + 1)
        }
    }
    printf("%-39s %-25s %-18s %'13d %'11d \n", $1, $2, $3, $4, $5)
}

NR <=3 {
    for(i = 1; i <=5; i++){
        topGrossFilms[NR][i] = $i
    }
}

NR == 3 {
    for(i = 1; i < NR; i++){
        if(topGrossFilms[i][5] > topGrossFilms[i + 1][5]){ #replace this crap with asort
            for(j = 1; j <= 5; j++){
                temp = topGrossFilms[i][j]
                topGrossFilms[i][j] = topGrossFilms[i + 1][j]
                topGrossFilms[i + 1][j] = temp
            }
        }
    }
}

NR > 3 {
    count = 0
    for(i = 1; i <= 3; i++){
        if($5 > topGrossFilms[i][5]){
            count++
            print count
        }
    }
    if(count >= 1){   #problem occuring in this general code block
        for(i = 1; i <= 5; i++){
            topGrossFilms[1][i] = $i
        }
    }
    if(count >= 2){ # or this code block, replace with asort
        for(i = 2; i < count; i++){
            for(j = 1; j <= 5; j++){
                temp = topGrossFilms[i][j]
                topGrossFilms[i][j] = topGrossFilms[i + 1][j]
                topGrossFilms[i + 1][j] = temp
            }
        }
    }
}

END{
    print("\nTop three grossing movies:")
    for(i = 1; i <= 3; i++){
        printf("%-39s %-25s %-18s %'13d %'11d \n", topGrossFilms[i][1],
            topGrossFilms[i][2], topGrossFilms[i][3], topGrossFilms[i][4], topGrossFilms[i][5])
    }
    print("Report generated by Noah Jenner")
}