#!/usr/bin/awk -f
BEGIN{
    FS=","
    printf("\tDocumentary\n")
    print("Top Genres and the Movies")
    count = 1
}
{
    indOfFirstQuote = index($1, "\"")
    firstPart = ""
    if(indOfFirstQuote != 0){
        firstPart = substr($1, 2, length($1))
        secondPart = substr($2, 1, length($2) - 1)
        $1 = firstPart "," secondPart
        for(i = 2; i <= NF; i++){
            $i = $(i + 1)
        }
    }
    
    if(index($2, "|") == 0){
        genres[$2][1]++
        genres[$2][genres[$2][1]] = $1
    }
    for(i in genres){
        print(genres[i])
    }
    
}
END{
    print("Report generated by Noah Jenner")
}